//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSecretRef) DeepCopyInto(out *EndpointSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSecretRef.
func (in *EndpointSecretRef) DeepCopy() *EndpointSecretRef {
	if in == nil {
		return nil
	}
	out := new(EndpointSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointsSecret) DeepCopyInto(out *EndpointsSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointsSecret.
func (in *EndpointsSecret) DeepCopy() *EndpointsSecret {
	if in == nil {
		return nil
	}
	out := new(EndpointsSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Heartbeat) DeepCopyInto(out *Heartbeat) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Heartbeat.
func (in *Heartbeat) DeepCopy() *Heartbeat {
	if in == nil {
		return nil
	}
	out := new(Heartbeat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Heartbeat) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeartbeatList) DeepCopyInto(out *HeartbeatList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Heartbeat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeartbeatList.
func (in *HeartbeatList) DeepCopy() *HeartbeatList {
	if in == nil {
		return nil
	}
	out := new(HeartbeatList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeartbeatList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeartbeatSpec) DeepCopyInto(out *HeartbeatSpec) {
	*out = *in
	out.EndpointsSecret = in.EndpointsSecret
	if in.ExpectedStatusCodeRanges != nil {
		in, out := &in.ExpectedStatusCodeRanges, &out.ExpectedStatusCodeRanges
		*out = make([]StatusCodeRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeartbeatSpec.
func (in *HeartbeatSpec) DeepCopy() *HeartbeatSpec {
	if in == nil {
		return nil
	}
	out := new(HeartbeatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeartbeatStatus) DeepCopyInto(out *HeartbeatStatus) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeartbeatStatus.
func (in *HeartbeatStatus) DeepCopy() *HeartbeatStatus {
	if in == nil {
		return nil
	}
	out := new(HeartbeatStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCodeRange) DeepCopyInto(out *StatusCodeRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCodeRange.
func (in *StatusCodeRange) DeepCopy() *StatusCodeRange {
	if in == nil {
		return nil
	}
	out := new(StatusCodeRange)
	in.DeepCopyInto(out)
	return out
}
